version: "3.8"
services:

  keycloak-db:
    image: postgres:13.4
    volumes:
      - ./keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak
      - backend
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    networks:
      - keycloak
    ports:
      - "8081:8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    depends_on:
      - keycloak-db

  app-db:
    image: postgres:13.4
    volumes:
      - ./app_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mosmngr"
      POSTGRES_USER: "mosmngr"
      POSTGRES_PASSWORD: "mosmngr"
      PGDATA: "/var/lib/postgresql/data/pgdata"

networks:
  keycloak:
  backend:
